version: '3.8'

services:
  media-renamer:
    build: .
    container_name: media-renamer
    ports:
      - "8090:8090"
    volumes:
      # 挂载媒体目录（根据实际情况修改）
      - /path/to/media:/data
      # 或者分别挂载
      # - /path/to/待整理:/data/待整理
      # - /path/to/电影:/data/电影
      # - /path/to/剧集:/data/剧集
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    networks:
      - media-network

networks:
  media-network:
    driver: bridge

# 使用说明:
# 1. 修改 volumes 中的路径为你的实际媒体目录
# 2. 运行: docker-compose up -d
# 3. 访问: http://localhost:8090
# 4. 查看日志: docker-compose logs -f
# 5. 停止: docker-compose down
