name: NAStool Docker

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Release version
        id: release_version
        run: |
          echo "app_version=$(echo $GITHUB_REF_NAME | sed 's/v\(.*\)/\1/')" >> $GITHUB_ENV

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Login GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:latest
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:${{ env.app_version }}
            ghcr.io/${{ github.repository_owner }}/nas-tools:latest
            ghcr.io/${{ github.repository_owner }}/nas-tools:${{ env.app_version }}
